upstream articles_api_servers {
  server articles_api;
}

upstream articles_search_servers {
  server articles_search;
}

upstream auth_api_servers {
  server auth_api;
}

server {
  listen 80;
  server_name localhost;

  access_log /dev/stdout;
  error_log /dev/stderr;
  
  location /articles/search/api/v1/ {
    proxy_pass http://articles_search_servers/api/v1//;
  }
 
  location /articles/api/v1/ {   
    access_by_lua_file /usr/local/openresty/lualib/resty/jwt-auth.lua;
    proxy_pass http://articles_api_servers/api/v1/;
  }

  location /auth/api/v1/ {
    proxy_pass http://auth_api_servers/api/v1/;
  }
}
