apiVersion: v1
kind: Service
metadata:
  name: articles-api-service-1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      #porta do serviço, porta é do servico do K8s, os outros podem podem acessar esse Service através dessa porta
      port: 8082
      #porta que ta exposta no pod, porta que configuramos na app
      targetPort: 5556
      #porta acessivel de fora do cluster
      nodePort: 31000
  selector:
    app: articles-api-pod